# Generated by Django 2.2.24 on 2021-09-04 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('area', models.PositiveIntegerField(blank=True, null=True, verbose_name='Area')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='Population')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('area', models.PositiveIntegerField(blank=True, null=True, verbose_name='Area')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='Population')),
                ('hospitals', models.PositiveIntegerField(blank=True, null=True, verbose_name='Country number of hospitals')),
                ('national_parks', models.PositiveIntegerField(blank=True, null=True, verbose_name='Country number of national parks')),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='app.Continent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('area', models.PositiveIntegerField(blank=True, null=True, verbose_name='Area')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='Population')),
                ('roads', models.PositiveIntegerField(blank=True, null=True, verbose_name='City number of roads')),
                ('trees', models.PositiveIntegerField(blank=True, null=True, verbose_name='City number of trees')),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='app.Continent')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='app.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
